/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnleitungRouteImport } from './routes/anleitung'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedPlayersIndexRouteImport } from './routes/_authenticated/players/index'
import { Route as AuthenticatedRankingsCreateRouteImport } from './routes/_authenticated/rankings/create'
import { Route as AuthenticatedRankingsRankingIdRouteImport } from './routes/_authenticated/rankings/$rankingId'
import { Route as AuthenticatedProfileCompleteRouteImport } from './routes/_authenticated/profile/complete'
import { Route as AuthenticatedPlayersPlayerIdRouteImport } from './routes/_authenticated/players/$playerId'
import { Route as AuthenticatedAdminDisputesRouteImport } from './routes/_authenticated/admin/disputes'
import { Route as AuthenticatedRankingsRankingIdReportRouteImport } from './routes/_authenticated/rankings/$rankingId_.report'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnleitungRoute = AnleitungRouteImport.update({
  id: '/anleitung',
  path: '/anleitung',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersIndexRoute =
  AuthenticatedPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRankingsCreateRoute =
  AuthenticatedRankingsCreateRouteImport.update({
    id: '/rankings/create',
    path: '/rankings/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRankingsRankingIdRoute =
  AuthenticatedRankingsRankingIdRouteImport.update({
    id: '/rankings/$rankingId',
    path: '/rankings/$rankingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileCompleteRoute =
  AuthenticatedProfileCompleteRouteImport.update({
    id: '/profile/complete',
    path: '/profile/complete',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersPlayerIdRoute =
  AuthenticatedPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDisputesRoute =
  AuthenticatedAdminDisputesRouteImport.update({
    id: '/admin/disputes',
    path: '/admin/disputes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRankingsRankingIdReportRoute =
  AuthenticatedRankingsRankingIdReportRouteImport.update({
    id: '/rankings/$rankingId_/report',
    path: '/rankings/$rankingId/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/anleitung': typeof AnleitungRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/profile/complete': typeof AuthenticatedProfileCompleteRoute
  '/rankings/$rankingId': typeof AuthenticatedRankingsRankingIdRoute
  '/rankings/create': typeof AuthenticatedRankingsCreateRoute
  '/players/': typeof AuthenticatedPlayersIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/rankings/$rankingId/report': typeof AuthenticatedRankingsRankingIdReportRoute
}
export interface FileRoutesByTo {
  '/anleitung': typeof AnleitungRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/profile/complete': typeof AuthenticatedProfileCompleteRoute
  '/rankings/$rankingId': typeof AuthenticatedRankingsRankingIdRoute
  '/rankings/create': typeof AuthenticatedRankingsCreateRoute
  '/players': typeof AuthenticatedPlayersIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/rankings/$rankingId/report': typeof AuthenticatedRankingsRankingIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/anleitung': typeof AnleitungRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/_authenticated/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/_authenticated/profile/complete': typeof AuthenticatedProfileCompleteRoute
  '/_authenticated/rankings/$rankingId': typeof AuthenticatedRankingsRankingIdRoute
  '/_authenticated/rankings/create': typeof AuthenticatedRankingsCreateRoute
  '/_authenticated/players/': typeof AuthenticatedPlayersIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/rankings/$rankingId_/report': typeof AuthenticatedRankingsRankingIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anleitung'
    | '/login'
    | '/register'
    | '/admin/disputes'
    | '/players/$playerId'
    | '/profile/complete'
    | '/rankings/$rankingId'
    | '/rankings/create'
    | '/players/'
    | '/profile/'
    | '/rankings/$rankingId/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/anleitung'
    | '/login'
    | '/register'
    | '/'
    | '/admin/disputes'
    | '/players/$playerId'
    | '/profile/complete'
    | '/rankings/$rankingId'
    | '/rankings/create'
    | '/players'
    | '/profile'
    | '/rankings/$rankingId/report'
  id:
    | '__root__'
    | '/_authenticated'
    | '/anleitung'
    | '/login'
    | '/register'
    | '/_authenticated/'
    | '/_authenticated/admin/disputes'
    | '/_authenticated/players/$playerId'
    | '/_authenticated/profile/complete'
    | '/_authenticated/rankings/$rankingId'
    | '/_authenticated/rankings/create'
    | '/_authenticated/players/'
    | '/_authenticated/profile/'
    | '/_authenticated/rankings/$rankingId_/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AnleitungRoute: typeof AnleitungRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anleitung': {
      id: '/anleitung'
      path: '/anleitung'
      fullPath: '/anleitung'
      preLoaderRoute: typeof AnleitungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/': {
      id: '/_authenticated/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof AuthenticatedPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rankings/create': {
      id: '/_authenticated/rankings/create'
      path: '/rankings/create'
      fullPath: '/rankings/create'
      preLoaderRoute: typeof AuthenticatedRankingsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rankings/$rankingId': {
      id: '/_authenticated/rankings/$rankingId'
      path: '/rankings/$rankingId'
      fullPath: '/rankings/$rankingId'
      preLoaderRoute: typeof AuthenticatedRankingsRankingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/complete': {
      id: '/_authenticated/profile/complete'
      path: '/profile/complete'
      fullPath: '/profile/complete'
      preLoaderRoute: typeof AuthenticatedProfileCompleteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/$playerId': {
      id: '/_authenticated/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof AuthenticatedPlayersPlayerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/disputes': {
      id: '/_authenticated/admin/disputes'
      path: '/admin/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AuthenticatedAdminDisputesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rankings/$rankingId_/report': {
      id: '/_authenticated/rankings/$rankingId_/report'
      path: '/rankings/$rankingId/report'
      fullPath: '/rankings/$rankingId/report'
      preLoaderRoute: typeof AuthenticatedRankingsRankingIdReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminDisputesRoute: typeof AuthenticatedAdminDisputesRoute
  AuthenticatedPlayersPlayerIdRoute: typeof AuthenticatedPlayersPlayerIdRoute
  AuthenticatedProfileCompleteRoute: typeof AuthenticatedProfileCompleteRoute
  AuthenticatedRankingsRankingIdRoute: typeof AuthenticatedRankingsRankingIdRoute
  AuthenticatedRankingsCreateRoute: typeof AuthenticatedRankingsCreateRoute
  AuthenticatedPlayersIndexRoute: typeof AuthenticatedPlayersIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedRankingsRankingIdReportRoute: typeof AuthenticatedRankingsRankingIdReportRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminDisputesRoute: AuthenticatedAdminDisputesRoute,
  AuthenticatedPlayersPlayerIdRoute: AuthenticatedPlayersPlayerIdRoute,
  AuthenticatedProfileCompleteRoute: AuthenticatedProfileCompleteRoute,
  AuthenticatedRankingsRankingIdRoute: AuthenticatedRankingsRankingIdRoute,
  AuthenticatedRankingsCreateRoute: AuthenticatedRankingsCreateRoute,
  AuthenticatedPlayersIndexRoute: AuthenticatedPlayersIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedRankingsRankingIdReportRoute:
    AuthenticatedRankingsRankingIdReportRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AnleitungRoute: AnleitungRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
